SET IDENTITY_INSERT [dbo].[Customer] ON
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (400, N'Juan', N'Dela Cruz', N'123 Main St', N'091273962644', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (401, N'Maria', N'Santos', N'456 Oak St', N'09128760599', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (402, N'Antonio', N'Gonzales', N'789 Pine St', N'091220343269', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (403, N'Sofia', N'Reyes', N'101 Elm St', N'091259945021', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (404, N'Ricardo', N'Lopez', N'555 Maple St', N'091254856987', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (405, N'Carmen', N'Torres', N'777 Cedar St', N'091295848276', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (406, N'Isabel', N'Mendoza', N'888 Oak St', N'091268122460', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (407, N'Felipe', N'Luna', N'999 Pine St', N'091234312736', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (408, N'Luz', N'Garcia', N'111 Elm St', N'091296825770', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (409, N'Andres', N'Ramos', N'222 Maple St', N'091279369031', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (410, N'Cecilia', N'Vega', N'333 Cedar St', N'091264145031', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (411, N'Eduardo', N'Perez', N'444 Oak St', N'091235307000', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (412, N'Imelda', N'Torres', N'555 Pine St', N'091217082814', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (413, N'Hector', N'Cruz', N'666 Elm St', N'091295284595', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (414, N'Cynthia', N'Gomez', N'777 Maple St', N'09129074709', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (415, N'Victor', N'Rodriguez', N'888 Cedar St', N'091216452308', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (416, N'Elena', N'Castillo', N'999 Oak St', N'091244092460', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (417, N'Fernando', N'Santana', N'123 Pine St', N'091244363861', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (418, N'Rosa', N'Ortega', N'456 Elm St', N'091244630693', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (419, N'Ramon', N'Valdez', N'789 Maple St', N'091294349609', N'Regular')
INSERT INTO [dbo].[Customer] ([customer_id], [FirstName], [LastName], [address], [contact], [type]) VALUES (420, N'Isabela', N'Mendoza', N'888 Oak St', N'091284291923', N'Regular')
SET IDENTITY_INSERT [dbo].[Customer] OFF
